apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: malayshikhar/user-service:1.0
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PASSWORD
          value: root
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 30001
  selector:
    app: user-service
